# Generated by Django 5.0.4 on 2024-05-16 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('admin_numrut', models.IntegerField(verbose_name='Numero de rut')),
                ('admin_dv', models.CharField(max_length=1, verbose_name='Digito verificador')),
                ('admin_p_nombre', models.CharField(max_length=25, verbose_name='Primer nombre')),
                ('admin_s_nombre', models.CharField(blank=True, max_length=25, null=True, verbose_name='Segundo Nombre')),
                ('admin_apaterno', models.CharField(max_length=25, verbose_name='Apellido paterno')),
                ('admin_apmaterno', models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellido materno')),
                ('admin_fec_nac', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('rut_emp', models.IntegerField()),
                ('razon_social', models.CharField(max_length=50, verbose_name='Razon social')),
                ('telefono2', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
